export const GameEvent = {
    LEVEL_COMPLETED: "LEVEL_COMPLETE",
    START_SCAN: "START_SCAN",
    SCAN_DONE: "SCAN_DONE",
    START_CHECKOUT: "START_CHECKOUT",
    CHECKOUT_SUCCESS: "CHECKOUT_SUCCESS",
    CHECKED_FAILED: "CHECKED_FAILED"
}